#Weather/Environment Module

##################################################
## Customize
##################################################



##################################################
## Groups
##################################################
group:
  environmental_panel:
    name: Environment
    entities:
      - sun.sun
      - sensor.moon

##################################################
## Components
##################################################
sun:

##################################################
## Weather Component
##################################################
weather:
  - platform: darksky
    api_key: !secret weather_darksky_api

##################################################
## Sensors
##################################################
sensor:
    #https://home-assistant.io/components/sensor.moon/
  - platform: moon

##################################################
## Binary Sensors
##################################################
binary_sensor:
    #https://home-assistant.io/components/binary_sensor.aurora/
  - platform: aurora

##################################################
## Automation
##################################################
