#Weather/Environment Module

##################################################
## Customize
##################################################

##################################################
## Components 
##################################################
sun:

##################################################
## Sensors
##################################################
sensor:



##################################################
## Binary Sensors
##################################################
binary_sensor:

    #https://home-assistant.io/components/binary_sensor.aurora/
  - platform: aurora
