#System Security Module

##################################################
## General
##################################################



##################################################
## Customize
##################################################


##################################################
## Groups
##################################################

##################################################
## Devices
##################################################

#
# Power cut detection, security panel
#
#

##################################################
## Sensors
##################################################

##################################################
## Automation
##################################################


##################################################
## Scripts
##################################################
